### PR TITLE
Improve mana regen tooltip, Fix regen while casting

### PR DESCRIPTION
**Pull request by ahrzou**
Sources :
- https://us.forums.blizzard.com/en/wow/t/is-my-maths-right-for-this-mana-5-vs-spirit/321047/3
- https://www.reddit.com/r/classicwow/comments/e9x3qp/

### CODE REVIEW

**Comment by Gurky-Turtle** [comment]
image
something seems to be off here says I should only get 13 mana per tick while casting but I get 38

**Comment by ahrzou** [comment]
More source for this :
https://vanilla-wow-archive.fandom.com/wiki/Mana_Regeneration

So I guess to summarize :
- Spirit leads to base regeneration depending on the class formula
- Spirit only provides mana while not being under the 5 seconds casting rule
- %While casting is additive, capped at 100% and allows the Spirit regeneration to continue during the 5 seconds casting rule
- MP5 affects everything, but needs to be converted to mana per 2 seconds

I'll make the modifications.

**Comment by ahrzou** [comment]
Seems to work consistently now:
image
image

**Comment by Gurky-Turtle** [comment]
Looks like it, thanks for taking a peak.

**Pull request merged**
